import { readFile, writeFile, readdir, access } from "node:fs/promises";
import { resolve, relative, dirname } from "node:path";
import assert from "node:assert/strict";

const root = process.cwd();
const skip = new Set([".git","node_modules",".next","artifacts","test-results","playwright-report","coverage"]);
async function collect(dir) {
  const result=[];
  for (const item of await readdir(dir,{withFileTypes:true})) {
    if (skip.has(item.name) || item.isSymbolicLink()) continue;
    const path=resolve(dir,item.name);
    if (item.isDirectory()) result.push(...await collect(path));
    else if (item.isFile() && /\.(md|json)$/.test(item.name)) result.push(path);
  }
  return result;
}
const load=async path=>JSON.parse(await readFile(resolve(root,path),"utf8"));
const status=await load("docs/INTEGRATION-STATUS.json");
const statuses=new Set(["SYNTHETIC_INTEGRATED","LOCAL_COMPONENT","DESIGN_ONLY","NOT_IMPLEMENTED","GATED_NOT_IMPLEMENTED","UNVERIFIED","LIVE_INTEGRATED"]);
assert.equal(status.schemaVersion,1);
assert.ok(Array.isArray(status.components) && status.components.length>0);
assert.equal(new Set(status.components.map(c=>c.id)).size,status.components.length);
for (const component of status.components) {
  assert.ok(statuses.has(component.status),"Unknown integration status: "+component.id);
  assert.ok(component.evidence && component.files.length>0,"Missing evidence: "+component.id);
  for (const file of component.files) await access(resolve(root,file));
}
if (status.allIntegrated) assert.ok(status.components.every(c=>c.status==="LIVE_INTEGRATED"),"allIntegrated conflicts with component status");
const capabilities=await load("ai/customer-assistance/policies/capabilities.v1.json");
if (capabilities.status==="DESIGN_ONLY") {
  assert.equal(capabilities.runtimeEnabled,false);
  assert.ok(capabilities.proposedTools.every(t=>t.enabled===false),"A design-only tool cannot be enabled");
}
const catalog=await load("ai/customer-assistance/knowledge/SERVICE-CATALOG.json");
if (catalog.deploymentStatus==="DESIGN_ONLY") assert.equal(catalog.approvedForProduction,false);
const registry=await load("legal/sources/registry.v1.json");
assert.equal(new Set(registry.sources.map(s=>s.id)).size,registry.sources.length);
for (const source of registry.sources) {
  if (source.legalRetrievalAllowed) assert.ok(source.version && source.checksum && source.reviewedBy && source.reviewedAt,
    "Legal retrieval enabled without version/review: "+source.id);
}
const labels={
  SYNTHETIC_INTEGRATED:"Integrado em demonstração sintética",LOCAL_COMPONENT:"Componente local testável",
  DESIGN_ONLY:"Especificado; sem runtime",NOT_IMPLEMENTED:"Não implementado",
  GATED_NOT_IMPLEMENTED:"Fase posterior; não implementado",UNVERIFIED:"Não verificado externamente",LIVE_INTEGRATED:"Integração real verificada",
};
const md="# Matriz de integração — "+status.review+"\n\n"+
  "<!-- Generated by npm run docs:generate from INTEGRATION-STATUS.json. -->\n\n"+
  "**Integração completa: "+(status.allIntegrated?"SIM":"NÃO")+". Produção/casos reais: "+(status.productionReady?"aprovada":"NÃO pronta")+".**\n\n"+
  "Esta matriz distingue componentes testados de integrações reais. Ela é um registro de evidência, não detecção automática de serviços. "+
  "Consulta e limites: [revisão de ponta a ponta](END-TO-END-REVIEW.md).\n\n"+
  "| Componente | Estado | Evidência / limite | Tickets |\n|---|---|---|---|\n"+
  status.components.map(c=>"| "+c.name+" | "+labels[c.status]+" | "+c.evidence+" | "+
    c.tickets.map(n=>"[FRO-"+n+"](MVP-BACKLOG.md)").join(", ")+" |").join("\n")+
  "\n\nAlterar primeiro [INTEGRATION-STATUS.json](INTEGRATION-STATUS.json) com evidência real; depois npm run docs:generate. "+
  "npm run check:docs recusa links locais quebrados e divergência entre JSON e esta tabela. "+
  "Não valida links externos, serviços vivos, aprovação jurídica, CI remota ou ausência universal de defeitos.\n";
const output=resolve(root,"docs/INTEGRATION-STATUS.md");
if (process.argv.includes("--write")) await writeFile(output,md);
else assert.equal(await readFile(output,"utf8"),md,"Integration Markdown drifted; run npm run docs:generate");
const files=await collect(root);
let links=0,jsonFiles=0,markdownFiles=0;
for (const file of files) {
  const body=await readFile(file,"utf8");
  if (file.endsWith(".json")) { JSON.parse(body); jsonFiles++; continue; }
  markdownFiles++;
  // Check local targets; external reachability and anchors require separate review.
  for (const match of body.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) {
    let target=match[1].trim().replace(/^<|>$/g,"");
    if (!target || target.startsWith("#") || /^[a-z][a-z0-9+.-]*:/i.test(target)) continue;
    target=decodeURIComponent(target.split("#")[0]);
    try { await access(resolve(dirname(file),target)); }
    catch { throw new Error("Broken local link: "+relative(root,file)+" -> "+target); }
    links++;
  }
}
console.log(markdownFiles+" Markdown, "+jsonFiles+" JSON and "+links+" local links checked; "+status.components.length+" integration records consistent.");
